import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ------------------------------------------------------------
// 🖋️ [SETTING] ส่วนการตั้งค่าฟอนต์ (Fonts Configuration)
// ------------------------------------------------------------
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ------------------------------------------------------------
// 🌍 [METADATA] ส่วนการตั้งค่าหัวข้อเว็บและคำอธิบาย (SEO)
// ------------------------------------------------------------
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ------------------------------------------------------------
// 🏗️ [LAYOUT] โครงสร้างหลักของเว็บไซต์ (Root Layout)
// ------------------------------------------------------------
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        {/* --------------------------------------------------------
            📦 [CHILDREN] จุดที่นำเนื้อหาจากหน้า "page.js" อื่นๆ มาแสดง 
            ทุกๆ หน้าที่คุณสร้างจะถูกนำมาวางไว้ตรงส่วนนี้อัตโนมัติ
            -------------------------------------------------------- */}
        {children}
        
      </body>
    </html>
  );
}